"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Urls = (function () {
    function Urls() {
        this.signInUser = 'api/Authorize/SignInUser';
        this.account = 'api/Authorize/GetAccount';
        this.signOutUser = 'api/Authorize/SignOutUser';
        this.registration = 'api/Authorize/Registration';
        this.confirmTheCode = 'api/Authorize/ConfirmTheCode';
        this.replacePassvord = 'api/Authorize/ReplacePassvord';
        this.getNewsActiveTop = 'api/News/GetNewsActiveTop';
        this.getNewsActive = 'api/News/GetNewsActive';
        this.codToEmail = 'api/Email/SingCodeToEmail';
        this.getAccount = 'api/Account/GetAccountInfo';
        this.addPlayer = 'api/Account/AddPlayer';
        this.dellPlayer = 'api/Account/DellPlayer';
        this.editAccountInfo = 'api/Account/EditAccountInfo';
        this.addImageAvatar = 'api/Image/AddImageAvatar';
        this.getTurnaments = 'api/Turnament/GetTurnaments';
        this.getTurnamentsForUser = 'api/Turnament/GetTurnamentsForUser';
        this.declareTournament = 'api/Turnament/DeclareTournament';
        this.command = 'api/Public/GetCommand';
        this.commandFilter = 'api/Public/GetCommandFilter';
        this.getPhoto = 'api/Public/GetPhoto';
        this.isAuth = 'api/AuthorizeAdmin/IsAuth';
        this.signInAdmin = 'api/AuthorizeAdmin/SignIn';
        this.signOutAdmin = 'api/AuthorizeAdmin/SignOutAdmin';
        this.getNewsInfo = 'api/NewsAdmin/GetNewsInfo';
        this.getNews = 'api/NewsAdmin/GetNews';
        this.dellNews = 'api/NewsAdmin/DellNews';
        this.addNews = 'api/NewsAdmin/AddNews';
        this.saveNews = 'api/NewsAdmin/SaveNews';
        this.activeNews = 'api/NewsAdmin/ActiveNews';
        this.addTurnament = 'api/TurnamentAdmin/AddTurnament';
        this.getTurnamentInfo = 'api/TurnamentAdmin/GetTurnamentInfo';
        this.dellTurnament = 'api/TurnamentAdmin/DellTurnament';
        this.getTurnamentCircle = 'api/TurnamentAdmin/GetTurnamentCircle';
        this.getTurnamentMixed = 'api/TurnamentAdmin/GetTurnamentMixed';
        this.getPlayerForTurnament = 'api/TurnamentAdmin/GetPlayerForTurnament';
        this.saveTurnamentInfo = 'api/TurnamentAdmin/SaveTurnamentInfo';
        this.changeStep = 'api/TurnamentAdmin/ChangeStep';
        this.changeStatusTour = 'api/TurnamentAdmin/ChangeStatusTour';
        this.changeArena = 'api/TurnamentAdmin/ChangeArena';
        this.changeDate = 'api/TurnamentAdmin/ChangeDate';
        this.acceptDeclare = 'api/TurnamentAdmin/AcceptDeclare';
        this.removeDeclare = 'api/TurnamentAdmin/RemoveDeclare';
        this.calculateTable = 'api/TurnamentAdmin/CalculateTable';
        this.calculateGroup = 'api/TurnamentAdmin/CalculateGroup';
        this.calculatePlayOff = 'api/TurnamentAdmin/CalculatePlayOff';
        this.divideForDay = 'api/TurnamentAdmin/DivideForDay';
        this.getArena = 'api/TurnamentAdmin/GetArena';
        this.completeGame = 'api/TurnamentAdmin/CompleteGame';
        this.closeTour = 'api/TurnamentAdmin/CloseTour';
        this.addGoals = 'api/TurnamentAdmin/AddGoals';
        this.addImgNewsTypeText = 'api/FileAdmin/AddImgNewsTypeText';
        this.addImgNewsTypePhoto = 'api/FileAdmin/AddImgNewsTypePhoto';
        this.addVideoForNews = 'api/FileAdmin/AddVideoForNews';
        this.dellPhoto = 'api/FileAdmin/DellPhoto';
    }
    return Urls;
}());
exports.Urls = Urls;
//# sourceMappingURL=urls.js.map