//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimp.DAL.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public System.Guid id_account { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string command_name { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
    }
}
