//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimp.DAL.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class circle_for_turnament
    {
        public System.Guid id_circle_for_turnament { get; set; }
        public System.Guid id_turnament { get; set; }
        public int numbr_circle { get; set; }
        public bool state_code { get; set; }
    }
}
