//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimp.DAL.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public System.Guid id_news { get; set; }
        public string title { get; set; }
        public string text { get; set; }
        public System.DateTime date { get; set; }
        public int type { get; set; }
        public bool top { get; set; }
        public bool active { get; set; }
        public Nullable<System.Guid> id_command_one { get; set; }
        public Nullable<System.Guid> id_command_two { get; set; }
    }
}
