//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimp.DAL.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public System.Guid id_player { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string middleName { get; set; }
        public int number { get; set; }
        public System.Guid id_account { get; set; }
    }
}
