//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimp.DAL.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class skip_match
    {
        public System.Guid id_skip_match { get; set; }
        public System.Guid id_turnament { get; set; }
        public System.Guid id_account { get; set; }
        public System.Guid id_player { get; set; }
        public System.DateTime date_appointment { get; set; }
    }
}
