//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimp.DAL.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class turnament
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int сontribution_tournament { get; set; }
        public int сontribution_game { get; set; }
        public int type { get; set; }
        public bool state_code { get; set; }
        public int step { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
    }
}
